# Generated by Django 3.2 on 2021-05-18 04:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=10)),
                ('acc', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.user')),
            ],
            options={
                'verbose_name': 'Coordinations',
                'verbose_name_plural': 'Coordinations',
            },
        ),
    ]
