# Generated by Django 3.2 on 2021-04-27 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210427_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinations',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
