# Generated by Django 3.2 on 2021-04-27 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_coordinations_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=10)),
                ('acc', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Coordinations',
        ),
    ]
